let myTeam = `Best Buds Besker and Richard`;

console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );
console.log( myTeam );